### PR TITLE
fix(highlight): forward search / matching in long lines

### LINKED ISSUE #161: forward search `/` incorrectly matches for long line
Repro steps

- create long line text file

i.e single-like package.json like attached in details
<details>
{"name":"@reactivex\/rxjs","version":"7.0.0-alpha.0","description":"Reactive Extensions for modern JavaScript","main":"index.js","sideEffects":false,"config":{"commitizen":{"path":"cz-conventional-changelog"}},"lint-staged":{"*.js":["eslint --fix","git add"],"*.ts":["tslint --fix","git add"]},"scripts":{"precommit":"lint-staged","commitmsg":"validate-commit-msg","build_all":"npm-run-all clean_dist copy_sources build_cjs build_esm5 build_esm2015 build_esm5_for_rollup build_umd build_types generate_packages","build_cjs":"npm-run-all clean_dist_cjs compile_dist_cjs","build_esm5":"npm-run-all clean_dist_esm5 compile_dist_esm5","build_esm5_for_rollup":"npm-run-all clean_dist_esm5_for_rollup compile_dist_esm5_for_rollup && mkdirp dist\/esm5_for_rollup\/node_modules","build_esm2015":"npm-run-all clean_dist_esm2015 compile_dist_esm2015","build_types":"npm-run-all clean_dist_types compile_dist_types","build_closure_core":"node .\/tools\/make-closure-core.js","build_global":"npm-run-all clean_dist_global build_esm5_for_rollup && mkdirp .\/dist\/global && node .\/tools\/make-umd-bundle.js && npm-run-all build_closure_core clean_dist_esm5_for_rollup","build_umd":"npm-run-all clean_dist_global && mkdirp .\/dist\/global && node .\/tools\/make-umd-bundle.js && npm-run-all build_closure_core","build_perf":"webdriver-manager update && npm-run-all build_cjs build_global perf","build_spec":"npm-run-all build_cjs generate_packages","build_spec_full":"npm-run-all build_spec","build:spec:browser":"echo \"Browser test is not working currently\" && exit -1 && webpack --config spec\/support\/webpack.mocha.config.js","clean_dist":"shx rm -rf .\/dist","clean_dist_cjs":"shx rm -rf .\/dist\/cjs","clean_dist_esm5":"shx rm -rf .\/dist\/esm5","clean_dist_esm5_for_rollup":"shx rm -rf .\/dist\/esm5_for_rollup","clean_dist_esm2015":"shx rm -rf .\/dist\/esm2015","clean_dist_global":"shx rm -rf .\/dist\/global","clean_dist_types":"shx rm -rf .\/dist\/typings","commit":"git-cz","compile_dist_cjs":"tsc -p .\/tsconfig\/tsconfig.cjs.json","compile_dist_esm5":"tsc -p .\/tsconfig\/tsconfig.esm5.json","compile_dist_esm2015":"tsc -p .\/tsconfig\/tsconfig.esm2015.json","compile_dist_esm5_for_rollup":"tsc -p .\/tsconfig\/tsconfig.esm5.rollup.json","compile_dist_types":"tsc -p .\/tsconfig\/tsconfig.types.json","copy_sources":"mkdirp dist && shx cp -r .\/src\/ .\/dist\/src","decision_tree_widget":"cd doc\/decision-tree-widget && npm run build && cd ..\/..","generate_packages":"node .make-packages.js","lint_perf":"eslint perf\/","lint_spec":"tslint -c tslint.json \"spec\/**\/*.ts\"","lint_src":"tslint -c tslint.json \"src\/**\/*.ts\"","lint":"npm-run-all --parallel lint_*","dtslint":"npm run build_types && dtslint --localTs .\/node_modules\/typescript\/lib --expectOnly .\/spec-dtslint","perf:micro":"node .\/perf\/micro\/index.js","prepublish":"shx rm -rf .\/typings && npm run build_all","postpublish":".\/docs_app\/scripts\/publish-docs.sh","publish_docs":".\/publish_docs.sh","test":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test_no_cache":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json TS_NODE_CACHE=false mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test_transpile_only":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json TS_NODE_TRANSPILE_ONLY=true mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test:browser":"echo \"Browser test is not working currently\" && exit -1 && npm-run-all build:spec:browser && opn spec\/support\/mocha-browser-runner.html","test:circular":"dependency-cruise --validate .dependency-cruiser.json -x \"^node_modules\" dist\/esm5","test:systemjs":"node integration\/systemjs\/systemjs-compatibility-spec.js","test:side-effects":"check-side-effects --test integration\/side-effects\/side-effects.json","test:side-effects:update":"npm run test:side-effects -- --update","tests2png":"mkdirp docs_app\/content\/img && mocha --opts spec\/support\/tests2png.opts \"spec\/**\/*-spec.ts\""},"repository":{"type":"git","url":"https:\/\/github.com\/reactivex\/rxjs.git"},"keywords":["Rx","RxJS","ReactiveX","ReactiveExtensions","Streams","Observables","Observable","Stream","ES6","ES2015"],"author":"Ben Lesh <ben@benlesh.com>","contributors":[{"name":"Ben Lesh","email":"ben@benlesh.com"},{"name":"Paul Taylor","email":"paul.e.taylor@me.com"},{"name":"Jeff Cross","email":"crossj@google.com"},{"name":"Matthew Podwysocki","email":"matthewp@microsoft.com"},{"name":"OJ Kwon","email":"kwon.ohjoong@gmail.com"},{"name":"Andre Staltz","email":"andre@staltz.com"}],"license":"Apache-2.0","bugs":{"url":"https:\/\/github.com\/ReactiveX\/RxJS\/issues"},"homepage":"https:\/\/github.com\/ReactiveX\/RxJS","dependencies":{"tslib":"^1.9.0"},"devDependencies":{"@angular-devkit\/build-optimizer":"0.4.6","@angular-devkit\/schematics":"^7.3.9","@types\/chai":"4.1.2","@types\/lodash":"4.14.102","@types\/mocha":"2.2.48","@types\/node":"9.4.5","@types\/sinon":"4.1.3","@types\/sinon-chai":"2.7.29","@types\/source-map":"^0.5.2","babel-polyfill":"6.26.0","benchmark":"2.1.0","chai":"4.1.2","check-side-effects":"0.0.20","color":"3.0.0","colors":"1.1.2","commitizen":"^4.0.3","cross-env":"5.1.3","cz-conventional-changelog":"1.2.0","dependency-cruiser":"^4.27.3","dtslint":"^0.7.4","escape-string-regexp":"1.0.5","eslint":"4.17.0","eslint-plugin-jasmine":"^2.10.1","fs-extra":"5.0.0","get-folder-size":"1.0.1","glob":"7.1.2","gm":"1.23.1","google-closure-compiler-js":"20170218.0.0","gzip-size":"4.1.0","klaw-sync":"3.0.2","lint-staged":"^8.1.6","lodash":"^4.17.15","minimist":"1.2.0","mkdirp":"0.5.1","mocha":"5.0.0","npm-run-all":"4.1.2","opn-cli":"3.1.0","platform":"1.3.5","promise":"8.0.1","rollup":"0.66.6","rollup-plugin-alias":"1.4.0","rollup-plugin-inject":"2.0.0","rollup-plugin-node-resolve":"2.0.0","shx":"0.2.2","sinon":"4.3.0","sinon-chai":"2.14.0","source-map-support":"0.5.3","systemjs":"^0.21.0","ts-node":"6.1.0","tsconfig-paths":"3.2.0","tslint":"5.9.1","tslint-etc":"1.5.0","tslint-no-toplevel-property-access":"0.0.2","tslint-no-unused-expression-chai":"0.0.3","typescript":"3.5.3","validate-commit-msg":"2.14.0","webpack":"^4.31.0"},"engines":{"npm":">=2.0.0"},"typings":".\/dist\/package\/Rx.d.ts"}
</details>

- forward search `/` to find text outside of current editor width
- check selected text visual

repro

### PR DESCRIPTION
**Pull request by xiyaowong**
- fix: cursor position after scrolling with incsearch
- refactor: remove viewport hack when in cmdline mode

---

- Close #1975
- Fix #161
- Related:
	- #1575

Because it involves a few historical matters and dealing with hacks, I won't go into too much detail. Here are some debugging notes.

### Cursor position for incsearch

| Commit History                                         | Nvim 0.9 | Nvim 0.10 |
| ------------------------------------------------------ | -------- | --------- |
| Add test                                               | ❌       | ✅        |
| Remove hack                                            | ❌       | ✅        |
| Update cursor position on window-scroll                | ❌       | ✅        |
| Fire cursor change event on window-scroll              | ❌       | ✅        |
| custom viewport changed event                          | ❌       | ✅        |
| after searching, perform a redraw and wait for a while | ✅       | ✅        |

### Forward search matching in long line

Only tested in Nvim 0.10.

### Conclusion

Highly recommend to upgrade to Nvim 0.10.

### CODE REVIEW

**Comment by ollien** [comment]
Am I reading your table correctly to mean that this breaks functionality for 0.9 users?

I'm not sure how I feel about breaking support for 0.9 so quickly after 0.10s release. Even our automated tests aren't updated to support it.

**Comment by xiyaowong** [comment]
> Am I reading your table correctly to mean that this breaks functionality for 0.9 users?
> 
> I'm not sure how I feel about breaking support for 0.9 so quickly after 0.10's release. Even our automated test runners aren't updated to support it. That said, if we already have precedent for staying on the bleeding edge, I guess it's not so bad?

After adding the test, there is a problem with nvim0.9. And this problem is not common.

**Comment by xiyaowong** [comment]
I tested it out, and indeed, this PR completely breaks the 0.9 search highlight. This is unacceptable.

**Comment by xiyaowong** [comment]
@ollien  Can you help test this pr in nvim0.9, it needs actual use for testing. And some problems are related to the platform. . .

**Comment by ollien** [comment]
@xiyaowong absolutely. I won't be in front of an IDE much for the next couple of days, so my testing may be a bit superficial, but I can definitely do some more soak testing otherwise. Are there any particular cases you'd like like to see tested?

Also, is this what you wanted to hold up the 1.11.5 release for? Maybe we can release that now and then push this as a minor version upgrade?

**Comment by xiyaowong** [comment]
> Are there any particular cases you'd like like to see tested?

Just use it normally

> Also, is this what you wanted to hold up the 1.11.5 release for?

Yeah.

> Maybe we can release that now and then push this as a minor version upgrade?

Agreed, this PR will still take some time to confirm.

File: runtime/lua/vscode-neovim/viewport.lua [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+  view.winid = api.nvim_get_current_win()
+  return view
+end
+
+local function setup_viewport_changed()
+  ---@type table<integer, WinView>
+  local view_cache = {}
+
+  api.nvim_set_decoration_provider(M.viewport_changed_ns, {
+    on_win = function()
```
Comment (ollien) [inline runtime/lua/vscode-neovim/viewport.lua:33]: Just for my education, what's the difference between this and the `WinScrolled` autocmd?

Comment (xiyaowong) [reply runtime/lua/vscode-neovim/viewport.lua:33]: WinScrolled won't be triggered under cmdline. We also need timely and accurate viewport information https://github.com/neovim/neovim/issues/28800#issuecomment-2117611542.

Comment (ollien) [reply runtime/lua/vscode-neovim/viewport.lua:33]: Huh, ok.

This comment befuddles me a little bit, but the reason for your change makes sense :)

> Well yes the cursor position in the current window changes for incsearch but the cursor position on the grid does not and should not(implicitly). What problem does this cause?

Comment (xiyaowong) [reply runtime/lua/vscode-neovim/viewport.lua:33]: - "grid cursor" refers to the **visible** cursor position.
- One grid includes not only the window viewport but also components like cmdline, statuscolumn, winbar, and so on. However, vscode-neovim doesn't (can't) need these components, we only dealing with the window viewport.

Comment (xiyaowong) [reply runtime/lua/vscode-neovim/viewport.lua:33]: You may notice that in the cursor manager, we only use `grid_cursor_goto` to detect changes in cursor position, but we actually use data from the viewport. With `ext_cmdline` enabledthe visual cursor position is managed by the UI, so there is no `grid_cursor_goto` event (In Nvim0.10).

File: runtime/lua/vscode-neovim/viewport.lua [hunk 2]
```diff
@@ -56,7 +56,12 @@ local function setup_viewport_changed()
 end
 
 function M.setup()
-  setup_viewport_changed()
+  -- Highlighting needs to wait for the viewport-changed event to complete.
+  -- When the UI attaches, there are numerous highlight events (hl_attr_define, grid_line) to process.
+  --
+  -- Without delaying the setup, the viewport-changed event will cause frequent
+  -- pauses in highlight processing, resulting in screen flickering.
+  vim.defer_fn(setup_viewport_changed, 2000)
```
Comment (ollien) [inline runtime/lua/vscode-neovim/viewport.lua:64]: Is there anything we can listen for to trigger this, rather than just waiting an arbitrary amount of time?

Comment (xiyaowong) [reply runtime/lua/vscode-neovim/viewport.lua:64]: The "viewport-changed" event complements the "win_viewport" event. In most cases, it wouldn't be a significant issue even without the "viewport-changed" event. The delay is more straightforward.

**Comment by xiyaowong** [comment]
I spent almost 5 hours, and couldn't find out why the failure of the virtual text highlighting test😢. 
Only know it passes when run alone (when it's the first test being run). There seems to be an issue with the method used for testing the highlight.

**Comment by xiyaowong** [comment]
😩😩😩

**Comment by xiyaowong** [comment]
Ready for review/test, but not ready for merge

File: src/viewport_manager.ts [hunk 3]
```diff
@@ -64,9 +70,6 @@ export class ViewportManager implements Disposable {
         col,
         topline,
     }: EventBusData<"viewport-changed">[0]) {
-        this.viewportChangedPromise?.resolve();
-        this.viewportChangedPromise = new ManualPromise();
```
Comment (ollien) [inline src/viewport_manager.ts]: Is there a reason you moved these outside of the function? If the issue is simply the `gridId` return causing the promise to be left as an unresolved `ManualPromise`, I think you could simplify this by doing

```ts
this.viewportChangedPromise?.resolve();
this.viewportChangedPromise = undefined;


const gridId = this.main.bufferManager.getGridIdForWinId(winid);
if (!gridId) {
  logger.warn(`Unable to update scrolled view. No grid for winId: ${winid}`);
  return;
}

this.viewportChangedPromise = new ManualPromise();
// ...
```

or am I missing something?

**Comment by ollien** [comment]
Things have mostly been fine here. There is one bug I'm seeing occasionally, which is that a highlighted keyword or curly brace will float in the editor (often very far from where I would expect it) when the window loads. I've reproduced it a couple times, but I've not managed to get a screenshot or anything of it yet

**Comment by xiyaowong** [comment]
It may be normal to have a little flaw. Many of them are caused by viewport. Is this problem brought by this pr?

**Comment by ollien** [comment]
I'd never seen it before, but given I can't easily repro it, I wouldn't sweat it

**Comment by xiyaowong** [comment]
Weired. This PR is just a more comprehensive ViewPort information, how can it cause new problems

**Comment by ollien** [comment]
> Weired. This PR is just a more comprehensive ViewPort information, how can it cause new problems

It might not be. It could be another PR from master :)

Like I said, don't sweat it

**Review by ollien — APPROVED** [review]
