### PR TITLE
fix(api): add delay for cursor synchronization in with_insert

### LINKED ISSUE #2398: bug: `vscode.with_insert()` doesn't preserve the selection after switching to insert mode
### Check the following:

- [x] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [x] I have read the vscode-neovim docs.
- [x] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

v0.11.0-dev-1706+g5371659524

### Operating system/version

macOS 15

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

In visual mode, `vscode.with_insert()` doesn't preserve the selection after switching to insert mode.

`keybinding.json`
```json
{
    "key": "cmd+d",
    "command": "vscode-neovim.lua",
    "args": [
      "local vscode = require('vscode')",
      "vscode.with_insert(function()",
      "  vscode.action('editor.action.addSelectionToNextFindMatch')",
      "end)"
    ]
}
```

### Steps To Reproduce

Notice after pressing `cmd+d`, the selection is canceled:

https://github.com/user-attachments/assets/a373a7fc-3b92-45c2-aec9-825a60a22cfa

### Expected Behavior

If in visual mode, `vscode.with_insert()` preserves the selection after switching to insert mode.

### PR DESCRIPTION
**Pull request by xiyaowong**
- fix #2398

### CODE REVIEW

File: runtime/lua/vscode/api.lua [hunk 1]
```diff
@@ -493,7 +493,11 @@ function M.with_insert(callback)
     api.nvim_win_set_cursor(0, end_pos)
     startinsert("<Esc>" .. (vim.o.selection ~= "exclusive" and "a" or "i"))
 
-    run_callback(ranges)
+    -- Wait for the cursor synchronization task to complete in VSCode
```
Comment (ollien) [inline runtime/lua/vscode/api.lua:496]: I'm not very familiar with this aspect of the codebase, but is there a more robust way to check the status of this task than just waiting for 30ms?

Comment (xiyaowong) [reply runtime/lua/vscode/api.lua:496]: I am also aware that this is unreliable. The debounce time is 5ms, so 30ms was chosen. There might be more reliable solutions, but this approach is certainly the simplest.

**Review by ollien — APPROVED** [review]

**Comment by wenfangdu** [comment]
@xiyaowong 👍👍👍
