### PR TITLE
fix: auto stop extension when starting nvim failed

### LINKED ISSUE #1702: When nvim fails to start, all the keys become unresponsive
When nvim fails to start, all the keys become unresponsive, vscode becomes unusable, The user experience is very poor.

### PR DESCRIPTION
**Pull request by xiyaowong**
Fixes #1702

Give more love to new vscode-neovim users from vscode who have never used nvim before.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export async function activate(context: vscode.ExtensionContext, isRestart = fal
         context.subscriptions.push(plugin);
         await plugin.init();
     } catch (e) {
-        vscode.window.showErrorMessage(`Unable to init vscode-neovim: ${(e as Error).message}`);
+        vscode.window.showErrorMessage(`[Failed to initialize neovim] ${e instanceof Error ? e.message : e}`);
```
Comment (justinmk) [inline src/extension.ts:28]:
```suggestion
        vscode.window.showErrorMessage(`[Failed to start nvim] ${e instanceof Error ? e.message : e}`);
```

**Review by theol0403 — APPROVED** [review]
