### PR TITLE
fix: Fix multi-byte character selection in Nvim 0.10 blockwise visual

### LINKED ISSUE #2166: In Nvim 0.10, block visual mode cannot correctly select CJK characters.
image

upstream issue: https://github.com/neovim/neovim/issues/29786

### PR DESCRIPTION
**Pull request by xiyaowong**
Since Nvim 0.10.0, `virtcol2col` changed from returning the last byte of a multi-byte character to returning the first byte. However, we need the column of the last byte, which is consistent with the selected region in Nvim.

Close #2166

### CODE REVIEW

**Comment by xiyaowong** [comment]
Is there any questions? There is a detailed discussion in the linked Neovim issue.

File: runtime/lua/vscode/util.lua [hunk 1]
```diff
@@ -79,4 +79,22 @@ function M.debounce(func, time)
   end
 end
 
+-- Since Nvim 0.10.0, `virtcol2col` changed from returning the last byte of a
+-- multi-byte character to returning the first byte. However, we need the column
+-- of the last byte, which is consistent with the selected region in Nvim.
+-- See https://github.com/neovim/neovim/issues/29786
+if fn.has("nvim-0.10.0") == 0 then
```
Comment (ollien) [inline runtime/lua/vscode/util.lua:86]: Will this break with nvim bumps the batch version?

**Comment by ollien** [comment]
@xiyaowong I was at work and couldn't answer until now, sorry :)

File: runtime/lua/vscode/util.lua (hunk 1 above)
Comment (xiyaowong) [reply runtime/lua/vscode/util.lua:86]: I didn't get what you meant.

Comment (ollien) [reply runtime/lua/vscode/util.lua:86]: This is checking whether or not the user is on nvim 0.10.0, right? What happens when a user upgrades to 0.10.1?

Comment (xiyaowong) [reply runtime/lua/vscode/util.lua:86]: It's OK, `:h has`. It's called "has", not "is" 😃

Comment (ollien) [reply runtime/lua/vscode/util.lua:86]: Yeah but wouldn't you want the substring to be "0.10."? (No trailing zero?) It might be better to parse this and see if it's 0.10 or greater, so we don't have to bump this when 0.11 releases

Comment (xiyaowong) [reply runtime/lua/vscode/util.lua:86]: has('nvim-0.10') and has('nvim-0.10.0') are the same; both indicate version 0.10.0 or higher. I prefer to use the full version number.

Comment (ollien) [reply runtime/lua/vscode/util.lua:86]: Ah, I misunderstood `has` and assumed it was a substring match!

**Review by ollien — APPROVED** [review]
