### PR TITLE
fix: queue text document change events

### LINKED ISSUE #2175: bug: nvim_win_set_cursor: Cursor position outside buffer
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14

### Describe the bug

When using with GitHub Copilot, clicking the answer box constantly throws `nvim_win_set_cursor: Cursor position outside buffer`.

### Steps To Reproduce

https://github.com/user-attachments/assets/1fc2cb50-5a5f-40b1-becd-b6b76d57eeae

### Expected Behavior

No errors.

### PR DESCRIPTION
**Pull request by xiyaowong**
During the initialization process, the document may continue to change, so by the end of initialization, our synchronized content is outdated and has lost the change events. This PR always caches document change events, filters out the outdated events after initialization, and then performs synchronization.

Please also check the code comments.

fix #2175

### CODE REVIEW

**Comment by xiyaowong** [comment]
Added description :)

File: src/document_change_manager.ts [hunk 1]
```diff
@@ -405,16 +461,18 @@ export class DocumentChangeManager implements Disposable {
 
         await actions.lua("handle_changes", bufId, changeArgs);
 
+        if (!isDirty) {
+            await this.client.request("nvim_buf_set_option", [bufId, "modified", false]);
```
Comment (theol0403) [inline src/document_change_manager.ts:465]: Why is this line also in 412?

**Review by theol0403 — APPROVED** [review]

File: src/document_change_manager.ts (hunk 1 above)
Comment (xiyaowong) [reply src/document_change_manager.ts:465]: The following events may occur:

1. The version remains unchanged, `contentChanges` is empty, and `isDirty` is false (the logic will not reach line 465, so `modified` needs to be set).
2. The version changes, `contentChanges` is not empty, and `isDirty` is false (this is an undo operation; therefore, after applying the changes, `modified` needs to be set manually).
