### PR TITLE
fix: handle `topline` in the `viewport-changed` event

### LINKED ISSUE #2194: bug: Ghost highlighted text appears when scrolling with relative line numbers enabled
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 11 Pro 23H2

### Describe the bug

The issue is demonstrated in the video linked below:

https://github.com/user-attachments/assets/c99f5407-2179-4253-b8f5-7053d4ee825f

Additional details:
- This bug occurs with `vscode-neovim.neovimClean` enabled (although this setting is not shown in the video).
- The issue persists regardless of the affinity setting.
- This behavior is believed to be recent, as it was not observed months ago.

### Steps To Reproduce

1. Set `"editor.lineNumbers": "relative"` in `settings.json`
2. Open a file in the editor
3. Search for text using the `/` key
4. Press Enter to close the search popup
5. Scroll the document using the mouse
6. Observe ghost highlighted text appearing

### Expected Behavior

No ghosts appear when scrolling.

### PR DESCRIPTION
**Pull request by gjf7**
Fixes #2194 

**Problem:**
Our highlight manager needs the correct offset of the current viewport. When scrolling with the mouse during `incsearch`, the offset sometimes becomes outdated. This happens because the `viewport-changed` event isn't triggered, and the 'win_viewport' event occurs after the `grid-line` event. As a result, `this.lineCells` becomes incorrect. This is problematic because we rely on accurate `this.lineCells` data when computing line highlights.

https://github.com/vscode-neovim/vscode-neovim/blob/160d7aa03cd72c59ab1a1cfa6e40a591298a549a/src/highlights/grid_line_handler.ts#L87

https://github.com/vscode-neovim/vscode-neovim/blob/160d7aa03cd72c59ab1a1cfa6e40a591298a549a/src/highlight_manager.ts#L105

**Solution:**
Trigger `viewport-changed` to get a up-to-date viewport

### CODE REVIEW

**Comment by xiyaowong** [comment]
Have you actually debugged the win_viewport event? In my memory, the topline has always been accurate.

**Comment by gjf7** [comment]
@xiyaowong Yes, I realized it's more of a timing issue. When `topline` is updated in 'on_win' event, the 'grid_line' handler is still using the old value to draw lines. Our 'win_viewport' handler is called after 'grid_line' with the correct topline value. I'm not sure if this is a good fix, but it seems work for me.

image

image

**Comment by xiyaowong** [comment]
@gjf7 Please use the following debug statement to check the output.

```diff
diff --git a/src/highlight_manager.ts b/src/highlight_manager.ts
index e2eff48..7c744c2 100644
--- a/src/highlight_manager.ts
+++ b/src/highlight_manager.ts
@@ -103,6 +103,7 @@ export class HighlightManager implements Disposable {
 
     private handleGridLine(gridId: number, row: number, col: number, cells: VimCell[]): void {
         const gridOffset = this.main.viewportManager.getGridOffset(gridId);
+        console.log(`gridOffset: ${gridId} => ${gridOffset.line}`);
         const drawLine = gridOffset.line + row;
         // Offset for the statuscolumn
         const startCol = col + gridOffset.character;
diff --git a/src/viewport_manager.ts b/src/viewport_manager.ts
index 2e8437c..cce1326 100644
--- a/src/viewport_manager.ts
+++ b/src/viewport_manager.ts
@@ -116,6 +116,7 @@ export class ViewportManager implements Disposable {
         switch (name) {
             case "win_viewport": {
                 for (const [grid, , topline, botline, curline, curcol] of args) {
+                    console.log(`win_viewport: ${grid} => ${topline}`);
                     const view = this.getViewport(grid);
                     const { line, col } = view;
                     view.topline = topline;
```

**Comment by gjf7** [comment]
I also print topline from `on_win`.

```diff
diff --git a/runtime/lua/vscode/viewport.lua b/runtime/lua/vscode/viewport.lua
index a8693cb..1ec0989 100644
--- a/runtime/lua/vscode/viewport.lua
+++ b/runtime/lua/vscode/viewport.lua
@@ -1,6 +1,7 @@
 local M = {}
 
 local api, fn = vim.api, vim.fn
+local vscode = require("vscode.api")
 
 M.event_group = api.nvim_create_augroup("vscode.viewport", { clear = true })
 M.viewport_changed_ns = api.nvim_create_namespace("vscode.viewport.changed")
@@ -36,22 +37,26 @@ local function setup_viewport_changed()
       view.botline = botline
       view.lnum = view.lnum - 1
 
+      local data = { value = "topline from on_win: " .. topline  }
+      fn.VSCodeExtensionNotify("print", data)
+
       local cache = view_cache[view.winid]
       if cache and vim.deep_equal(view, cache) then
         return
       end
       view_cache[view.winid] = view
 
+
       --#region XXX: Temporary fix for #2165
       -- Avoid unnecessary notifications
       -- For highlighting #1976 #2194
       local leftcol_changed = cache and cache.leftcol ~= view.leftcol
-      local topline_changed = cache and cache.topline ~= view.topline
+      -- local topline_changed = cache and cache.topline ~= view.topline
       -- For cursor position #1971
       local cursor_changed = cache
         and (cache.lnum ~= view.lnum or cache.col ~= cache.col)
         and api.nvim_get_mode().mode == "c"
-      if not leftcol_changed and not cursor_changed and not topline_changed then
+      if not leftcol_changed and not cursor_changed then
         return
       end
       --#endregion
diff --git a/src/highlight_manager.ts b/src/highlight_manager.ts
index e2eff48..5d0148d 100644
--- a/src/highlight_manager.ts
+++ b/src/highlight_manager.ts
@@ -25,9 +25,16 @@ export class HighlightManager implements Disposable {
             this.groupStore,
             eventBus.on("redraw", this.handleRedraw, this),
             eventBus.on("flush-redraw", this.handleRedrawFlush, this),
+            // @ts-ignore
+            eventBus.on("print", this.print, this),
         );
     }
 
+    // @ts-ignore
+    private print(data: Record<any, any>) {
+        console.log(data[0].value);
+    }
+
     // Get or create a HighlightGrid for the given gridId
     private getGrid(gridId: number): HighlightGrid {
         if (!this.highlightGrids.has(gridId)) {
@@ -103,6 +110,7 @@ export class HighlightManager implements Disposable {
 
     private handleGridLine(gridId: number, row: number, col: number, cells: VimCell[]): void {
         const gridOffset = this.main.viewportManager.getGridOffset(gridId);
+        console.log(`gridOffset: ${gridId} => ${gridOffset.line}`);
         const drawLine = gridOffset.line + row;
         // Offset for the statuscolumn
         const startCol = col + gridOffset.character;
diff --git a/src/viewport_manager.ts b/src/viewport_manager.ts
index 2e8437c..db007f0 100644
--- a/src/viewport_manager.ts
+++ b/src/viewport_manager.ts
@@ -119,6 +119,7 @@ export class ViewportManager implements Disposable {
                     const view = this.getViewport(grid);
                     const { line, col } = view;
                     view.topline = topline;
+                    console.log(`win_viewport: ${grid} => ${topline}`);
                     view.botline = botline;
                     view.line = curline;
                     view.col = curcol;
```

1. open a file with this content.

```
Copyright (c) <year> <owner>. 

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

```
2. search `in` and scroll using mouse, until incorrect highlights are showing up

You can see the offset still old value `0`, and topline from `on_win` is `1`. `win_viewport` is triggered after `grid_line` event.

image

File: runtime/lua/vscode/viewport.lua [hunk 1]
```diff
@@ -44,13 +44,14 @@ local function setup_viewport_changed()
 
       --#region XXX: Temporary fix for #2165
       -- Avoid unnecessary notifications
-      -- For highlighting #1976
+      -- For highlighting #1976 #2194
       local leftcol_changed = cache and cache.leftcol ~= view.leftcol
+      local topline_changed = cache and cache.topline ~= view.topline
```
Comment (xiyaowong) [inline runtime/lua/vscode/viewport.lua:49]:
```suggestion
      -- For highlighting #1976
      local leftcol_changed = cache and cache.leftcol ~= view.leftcol
      -- For highlighting #2194
      local topline_changed = cache and cache.topline ~= view.topline
```

**Review by xiyaowong — CHANGES_REQUESTED** [review]

**Comment by xiyaowong** [comment]
`on_win` is executed before redraw, so it definitely has the latest data. The problem now is why the win_viewport data is incorrect, and also, I can't reproduce this issue.

Please print and check the sequence of nvim events here. There might be a bug in our eventBus. 🤔 
https://github.com/vscode-neovim/vscode-neovim/blob/160d7aa03cd72c59ab1a1cfa6e40a591298a549a/src/main_controller.ts#L302

**Comment by gjf7** [comment]
I checked the event order. Neovim sends 'win-viewport' after 'grid-line'. If we only use 'topline' from 'win_viewport' ('viewport_changed' doesn't fire due to filtering condition) This causes the wrong 'topline' value.

As a temporary fix, I've tested it on my Mac, and it works.

image
image

**Review by xiyaowong — APPROVED** [review]
