### PR TITLE
fix: set correct cwd for WSL

### LINKED ISSUE #520: Working directory not set correctly with WSL installation
Right now, `:pwd` gives me `/mnt/c/<user>/AppData/Local/Programs/Microsoft VSCode` in every document and workspace. I think the working directory should actually be the current workspace, to match the behavior of VSCode's integrated terminal.

I'm using a Neovim installation on WSL. The working directory is the same regardless of whether I open a file in WSL or Windows.

### PR DESCRIPTION
**Pull request by xiyaowong**
Close #520

### CODE REVIEW

**Review by theol0403 — APPROVED** [review]

File: src/main_controller.ts [hunk 1]
```diff
@@ -85,9 +87,9 @@ export class MainController implements vscode.Disposable {
         ];
 
         const workspaceFolder = vscode.workspace.workspaceFolders;
-        const cwd = workspaceFolder && workspaceFolder.length ? workspaceFolder[0].uri.fsPath : undefined;
-        if (cwd && !config.useWsl && !vscode.env.remoteName) {
-            args.push("-c", `cd ${cwd}`);
+        const cwd = workspaceFolder?.length ? workspaceFolder[0].uri.fsPath : undefined;
+        if (cwd && !vscode.env.remoteName) {
+            args.push("-c", `cd ${config.useWsl ? wslpath(cwd) : cwd}`);
```
Comment (justinmk) [inline src/main_controller.ts:92]: `cd` is somewhat clumsy, should we pass `cwd` to `spawn()`?  https://nodejs.org/api/child_process.html#child_processspawncommand-args-options

Comment (xiyaowong) [reply src/main_controller.ts:92]: Haha, I realized this after the merger. Too lazy to make changes.
