### PR TITLE
fix: ignore editors without `ViewColumn` in nvim-0.10

### LINKED ISSUE #2407: Stuck at Syncing Layout: Syncing Visible Editors
Type: <b>Bug</b>

Steps to reproduce:  
1. Write some code and go to normal mode.
2. Open GitHub Copilot 
3. Generate some code
4. Click on the code generated by it.
4. Focus on your own code and try to go back to insert mode.

Expected: I should be able to type and change between insert and normal modes.

Actual: Pressing i ( for insert mode) does not do anything. There is a warning at the bottom-right side:

Additional info: Only thing that can be done is disabling the extension and enabling it again.

Extension version: 1.18.18
VS Code version: Code 1.97.2 (Universal) (e54c774e0add60467559eb0d1e229c6452cf8447, 2025-02-12T23:20:35.343Z)
OS version: Darwin arm64 24.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|17, 17, 16|
|Memory (System)|18.00GB (0.53GB free)|
|Process Argv|. --crash-reporter-id d916d4e5-5c43-4ce6-9032-3a3bc964cc74|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt551:31249599
vscod805cf:30301675
binariesv615:30325510
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
iacca1:31171482
5fd0e150:31155592
dwcopilot:31170013
6074i472:31201624
dwoutputs:31242946
customenabled:31248079
hdaa2157:31222309
copilot_t_ci:31222730
jda6j935:31233686
copilothoveron:31248524

```

</details>

### PR DESCRIPTION
**Pull request by xiyaowong**
Ignore editors without a ViewColumn in Neovim 0.10 and above to avoid issues caused by too many editors leading to RPC problems.

At present, [this](https://github.com/vscode-neovim/vscode-neovim/pull/2394/commits/54bb04ed3e0d5adc65e7589e8d4add91696c03f2) is the simplest and most useful approach. The difference is that keeping the activeEditor synchronized at all times is more accurate.

fix #2407

### CODE REVIEW

**Comment by xiyaowong** [comment]
Before merging this PR, please merge PR #2469 first.

**Comment by ollien** [comment]
Can you help me understand how this will help? Your previous comments on #2394 mentioned that this was likely an illusion, as it doesn't solve the root of the problem.

**Comment by xiyaowong** [comment]
> Can you help me understand how this will help? Your previous comments on #2394 mentioned that this was likely an illusion, as it doesn't solve the root of the problem.

Yes, what I said still holds true, but this [comment](https://github.com/vscode-neovim/vscode-neovim/issues/2407#issuecomment-2816356893) also makes sense.

File: src/buffer_manager.ts [hunk 1]
```diff
@@ -612,9 +617,17 @@ export class BufferManager implements Disposable {
                 this.isLayoutOutdated = false;
                 const token = this.syncLayoutSource?.token;
 
-                const visibleEditors = [...window.visibleTextEditors];
                 const activeEditor = window.activeTextEditor;
 
+                // NOTE: See #2407
```
[the remark this answers is not in the document]
Comment (xiyaowong) [reply src/buffer_manager.ts]: ok, done

File: src/buffer_manager.ts [hunk 2]
```diff
@@ -612,9 +617,20 @@ export class BufferManager implements Disposable {
                 this.isLayoutOutdated = false;
                 const token = this.syncLayoutSource?.token;
 
-                const visibleEditors = [...window.visibleTextEditors];
                 const activeEditor = window.activeTextEditor;
 
+                // NOTE: Issue #2407 is caused by a current bug in nvim when handling RPC requests.
```
Comment (justinmk) [inline src/buffer_manager.ts:622]:
```suggestion
                // NOTE: Issue #2407 is caused by a current bug in nvim when handling RPC requests. https://github.com/neovim/neovim/issues/31316
```

File: src/buffer_manager.ts [hunk 3]
```diff
@@ -612,9 +617,20 @@ export class BufferManager implements Disposable {
...
+                // To mitigate it, we exclude editors without a ViewColumn
+                // (e.g., input boxes, chat code blocks) to reduce sync operations.
+                // These editors are usually temporary, so the impact is minimal.
```
Comment (justinmk) [inline src/buffer_manager.ts:625]: Great explanation!

**Review by justinmk — APPROVED** [review]

**Review by theol0403 — APPROVED** [review]

**Comment by xiyaowong** [comment]
It broke the window switching test for output and notebook. However, it doesn't affect normal usage, since `activeEditor` is always kept in sync. Maybe consider adding these two commonly used editors to the whitelist filter?
