### PR TITLE
fix: rapid cmdline_show/cmdline_hides would not be handled logically

### LINKED ISSUE #2079: bug: vim-sandwich stops working since 1.14
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Windows 7

### Describe the bug

I have been using https://github.com/machakann/vim-sandwich in neovim and vscode-neovim since day 1. It has been working perfectly. But it stops working since v1.14 (the last version it is still working is 1.13.1).

When try to delete / replace pair of parentheses, it just alter the texts outside of the selected scope.   

### Steps To Reproduce

1. Install vim-sandwich => `Plug 'machakann/vim-sandwich'`
2. Create a *.md file with 

```
"test_1"
"test_2"
"test_3"
```
3. Run `sr"'` in normal mode. It should replace `"` pair into `'` pair. 
4. Run `sd"` in normal mode. It should delete `"` pair

vim-sandwich

### Expected Behavior

Run `sr"'` in normal mode. It should replace `"` pair into `'` pair. 
Run `sd"` in normal mode. It should delete `"` pair

### PR DESCRIPTION
**Pull request by ollien**
Replaces #2081
Fixes #2079 

I came up with [this idea](https://github.com/vscode-neovim/vscode-neovim/pull/2081#issuecomment-2157087672) a little while ago, but haven't had the chance to sit down and implement it. Ultimately, most problems with our two-way cmdline sync originats from the fact that a cmdline_hide can be sent before the quickpick actually executes a hide event, or vice versa. Attempting to  manipulate the events to "ignore" is error prone, given this ordering problem. 

To repeat myself a bit from the linked comment, the "idea" is that we can handle cmdline events in batches. Once we receive a cmdline_hide event at level 1 (i.e. no nested command lines), we can consider the current batch "terminated", and begin queueing up events. Then, when we get a VSCode "hide" event, we can flush the batch, and continue processing events. 

A screencast showing some usage of the vim sandwich plugin, and various simple commandline usages

https://github.com/vscode-neovim/vscode-neovim/assets/977151/9fb86d8c-d180-470d-910f-ab18d046c574

### CODE REVIEW

**Review by theol0403 — APPROVED** [review]
Great work on this, working for me!

There are several typos in the comments, can you go through them (and also try to make less verbose where applicable).

File: src/cmdline/cmdline_queue.ts [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+ * of how the JS event loop works, but it's easiest to think of it as a race) between quickpick hide events and cmdline_* events from nvim. If there is a
+ * cmdline_hide, followed immediately by a cmdline_show, we may call hide() on the quickpick, but onHide will not
+ * be fired until our event handlers have completed execution, leading to bizarre and confusing states. As such,
+ * we "queue" events until we know for sure that the quickpick has bene hidden, and then allow them to be flushed back
+ * to the cmdline_manager.
+ */
+export class CmdlineQueue {
+    private pendingBatches: EventBusData<"redraw">[][] = [];
+    private needFlush: boolean = false;
+    private level: number | null = null;
```
Comment (theol0403) [inline src/cmdline/cmdline_queue.ts:17]: Are we tracking level in two places now?

Comment (ollien) [reply src/cmdline/cmdline_queue.ts:17]: Unfortunately, yes. This gave me a bit of an ick, but they're acutally used for different purposes; this will not always be in sync with the `level` on the cmdline manager itself. I could probably name this something better.

**Comment by ollien** [comment]
> There are several typos in the comments, can you go through them (and also try to make less verbose where applicable).

Heh, sorry about that. I wrote this before breakfast so I wasn't at my sharpest writing-wise :sweat_smile:

File: src/cmdline/cmdline_queue.ts (hunk 1 above)
Comment (ollien) [reply src/cmdline/cmdline_queue.ts]: Hopefully the new naming makes it a bit clearer.

**Review by theol0403 — APPROVED** [review]
