### PR TITLE
fix(buffer): prefer real path as buffer name

### LINKED ISSUE #798: Current file name in % register is invalid
The percent register `%` has an invalid file name which makes it unusable.

For example, I wanted to quickly run my current file through node, so I ran the following command:

```
:! node %
```

which got expanded as:

```
VSCode-Neovim:

:! node __vscode_neovim__-file:///Users/path/to/my/file.js
```

That prefix obviously made the command fail. Is that a hard requirement to have to make this extension work?

### PR DESCRIPTION
**Pull request by xiyaowong**
- [x] WSL
- [x] Test behavior in remote development

Resolve #798

### CODE REVIEW

File: runtime/lua/vscode-neovim/internal.lua [hunk 1]
```diff
@@ -268,4 +268,15 @@ function M.start_visual(buf, anchor, active)
   api.nvim_feedkeys((v == "V" or v == "\x16") and "gvv" or "gv", "n", false)
 end
 
+---Translate from a Windows path to a WSL path
+---@param path string
+---@return string?
+function M.wslpath(path)
+  local f = io.popen(("wslpath '%s'"):format(path))
+  if f then
```
Comment (justinmk) [inline runtime/lua/vscode-neovim/internal.lua:276]: wouldn't you want an error instead of silently ignoring a failure?

File: runtime/lua/vscode-neovim/internal.lua [hunk 2]
```diff
@@ -268,4 +268,15 @@ function M.start_visual(buf, anchor, active)
   api.nvim_feedkeys((v == "V" or v == "\x16") and "gvv" or "gv", "n", false)
 end
 
+---Translate from a Windows path to a WSL path
+---@param path string
+---@return string?
+function M.wslpath(path)
```
Comment (theol0403) [inline runtime/lua/vscode-neovim/internal.lua:274]: Why do we need this, can't we use the ts wsl function?

Comment (xiyaowong) [reply runtime/lua/vscode-neovim/internal.lua:274]: Executing wsl.exe creates a new connection to the instance each time, which is unnecessary. Since nvim is already running in the instance, it is more efficient and reasonable to use it as a bridge to execute Linux commands.

**Review by theol0403 — APPROVED** [review]
